# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-Pod-Coverage
version:      1.08
version_from: Coverage.pm
installdirs:  site
requires:
    Pod::Coverage:                 0
    Test::Builder::Tester:         0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
